### PR TITLE
add a restart button and would allow moving of stacks of cards in foundations

### PR DESCRIPTION
**Pull request by MagicMaxMark**
I added a restart button and made it so you can now select multiple cards and they can now be moved as a stack between foundations.

### CODE REVIEW

**Review by SHELLEYJ32-zz — CHANGES_REQUESTED** [review]
Clicking on Restart button throws an error: MissingReferenceException: The object of type 'GameObject' has been destroyed but you are still trying to access it.
Config.Update () (at Assets/Scripts/Config.cs:53)

**Comment by MagicMaxMark** [comment]
fixed error

**Comment by SHELLEYJ32-zz** [comment]
Whenever a card in the foundation and reactor is clicked, it throws an error.
Tag: FoundationScript is not defined.
UnityEngine.GameObject:CompareTag(String)
UtilsScript:Click() (at Assets/Scripts/UtilsScript.cs:122)
UtilsScript:Update() (at Assets/Scripts/UtilsScript.cs:35)

**Comment by MagicMaxMark** [comment]
I forgot to push :(

**Comment by SHELLEYJ32-zz** [comment]
[No longer a problem after Sophia's commit] Clicking on Reactor before selecting a card to match now gives NullPointerException errors. I have put this as a separate card on Trello.

**Pull request merged**
